### ISSUE TITLE
Not working in Python code

### ISSUE THREAD

**Issue by ygoe** [jgclark/vscode-todo-highlight#74] opened 2023-04-20 09:56 UTC
I'm using this extension for some time now. It works fine in .js and .php files, but shows no effect in .py files. I think it worked before, but I'm not writing Python often so I can say when.

The current version in 2.0.8 with VSCode 1.77.3 on Windows.

**Comment by alkatar21** [comment] 2023-04-20 10:09
Duplicate of #69. This is the case because `include` and `exclude` were not correctly used before. This has been fixed in 2.0.8. 

However, as can be seen at https://github.com/jgclark/vscode-todo-highlight#configuration, highlighting is enabled by default for only a few file types. Adding `"**/*.py"` to `todohighlight.include` should fix this for now. The setting needs to be reconsidered, as noted in #72, so that highlighting is enabled by default for most file types in the future.

**Comment by ygoe** [comment] 2023-04-20 10:18
Thank you, I can fix it now. But it's annoying to define all the file types I'm working with in the several projects. It can be a lot. Setting any type replaces the defaults, too.

**Comment by alkatar21** [comment] 2023-04-20 10:19
Yes, hopefully that will be improved as soon as there is time.

**Comment by jgclark** [comment] 2023-04-20 10:25
@ygoe Yes, this will be improved shortly. In fact I coded up #72 yesterday, and I hope over the weekend it can be tested by some others and then released.

**Closed** 2023-04-20 10:25 UTC
